spring:
  profiles:
    active: @environment@
  mail:
    host: smtp.gmail.com
    port: 587
    username: "unijira20@gmail.com"
    password: "mascalzonef"
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true


logging:
  level:
    root: ERROR
    org.springframework.web: ERROR
    org.springframework.security: ERROR

server:
  port: 7080

config:
  environment: @environment@
  locale: "it"
  routes:
    public: "/auth/authenticate;/auth/register;/auth/active;/auth/refresh;/auth/password-reset-with-token;/auth/available"



