logging:
  level:
    - it.unical.unijira: ERROR

spring:
  datasource:
    username: sa
    password:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/unijira
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      dialect: org.hibernate.dialect.MySQL5Dialect


server:
  compression:
    enabled: true

config:
  baseURL: "https://unijira.com"