spring:
  profiles:
    active: @environment@
  mail:
    host: smtp.gmail.com
    port: 587
    username: "unijira20@gmail.com"
    password: "mascalzonef"
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true


logging:
  level:
    - org.springframework.web: ERROR
    - org.springframework.boot: ERROR

platform:
  locale:
    language: "it"

server:
  port: 7080
